# -*- coding: utf-8 -*-
"""ALPROTTS4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QVUgyd6-m9qV3dgSZ9pL0nlcyVgp0zK6
"""

main
# Program Pencatatan Hasil Panen Digital
# Fitur: input_data() -- Anggota A
# Fitur: laporan() -- Anggota B

data_panen = {
    "Padi": 120,
    "Jagung": 80,
    "Kedelai": 45
}


def hitung_total(data):
    """Menghitung total hasil panen (dalam kg) dari seluruh komoditas."""
    return sum(data.values())


def input_data():
    """
    Meminta pengguna memasukkan data hasil panen baru (nama komoditas & jumlah),
    lalu menambahkan atau memperbarui data pada dictionary data_panen.
    """
    komoditas = input("Masukkan nama komoditas: ").strip().title()

    while True:
        jumlah_input = input(f"Masukkan jumlah hasil panen {komoditas} (kg): ").strip()
        try:
            jumlah = float(jumlah_input)
            if jumlah < 0:
                print("Jumlah tidak boleh negatif. Coba lagi.")
                continue
            break
        except ValueError:
            print("Input harus berupa angka. Coba lagi.")

    if komoditas in data_panen:
        print(f"Komoditas '{komoditas}' sudah ada dengan jumlah {data_panen[komoditas]} kg.")
        data_panen[komoditas] += jumlah
        print(f"Data diperbarui: {komoditas} sekarang menjadi {data_panen[komoditas]} kg.")
    else:
        data_panen[komoditas] = jumlah
        print(f"Data baru ditambahkan: {komoditas} sebanyak {jumlah} kg.")


def tampilkan_data():
    """Menampilkan seluruh data hasil panen yang tersimpan saat ini."""
    print("\n=== Data Hasil Panen Saat Ini ===")
    for komoditas, jumlah in data_panen.items():
        print(f"{komoditas}: {jumlah} kg")
    print(f"Total: {hitung_total(data_panen)} kg\n")


# ==================== FITUR LAPORAN ====================

def laporan():
    """
    Menampilkan laporan lengkap hasil panen yang mencakup:
    - Total hasil panen
    - Rata-rata hasil panen per komoditas
    - Komoditas dengan hasil tertinggi & terendah
    - Persentase kontribusi setiap komoditas
    - Status kelayakan panen (berdasarkan rata-rata)
    """
    if not data_panen:
        print("\n[!] Belum ada data panen untuk dilaporkan.")
        return

    total = hitung_total(data_panen)
    jumlah_komoditas = len(data_panen)
    rata_rata = total / jumlah_komoditas

    # Mencari komoditas tertinggi dan terendah
    komoditas_tertinggi = max(data_panen, key=data_panen.get)
    komoditas_terendah = min(data_panen, key=data_panen.get)

    # Header laporan
    print("\n" + "=" * 50)
    print("         LAPORAN HASIL PANEN DIGITAL")
    print("=" * 50)
    print(f"Jumlah Komoditas   : {jumlah_komoditas}")
    print(f"Total Hasil Panen  : {total:.2f} kg")
    print(f"Rata-rata Panen    : {rata_rata:.2f} kg/komoditas")
    print("-" * 50)

    # Detail per komoditas
    print("\n>> Rincian Per Komoditas:")
    print(f"{'No':<4}{'Komoditas':<15}{'Jumlah (kg)':<15}{'Kontribusi':<12}")
    print("-" * 50)

    # Urutkan dari jumlah terbesar ke terkecil
    data_urut = sorted(data_panen.items(), key=lambda x: x[1], reverse=True)

    for i, (komoditas, jumlah) in enumerate(data_urut, start=1):
        persentase = (jumlah / total) * 100
        print(f"{i:<4}{komoditas:<15}{jumlah:<15.2f}{persentase:.2f}%")

    print("-" * 50)

    # Analisis
    print("\n>> Analisis:")
    print(f"  • Komoditas Tertinggi : {komoditas_tertinggi} ({data_panen[komoditas_tertinggi]} kg)")
    print(f"  • Komoditas Terendah  : {komoditas_terendah} ({data_panen[komoditas_terendah]} kg)")

    # Status kelayakan
    if total >= 300:
        status = "SANGAT BAIK - Produksi melimpah"
    elif total >= 150:
        status = "BAIK - Produksi stabil"
    else:
        status = "PERLU DITINGKATKAN - Produksi rendah"

    print(f"  • Status Panen        : {status}")

    # Rekomendasi
    print("\n>> Rekomendasi:")
    if data_panen[komoditas_terendah] < rata_rata:
        print(f"  - Tingkatkan produksi '{komoditas_terendah}' karena berada di bawah rata-rata.")
    if data_panen[komoditas_tertinggi] > rata_rata * 1.5:
        print(f"  - Pertahankan produktivitas '{komoditas_tertinggi}' yang sangat baik.")
    print("  - Lakukan evaluasi berkala terhadap hasil panen.")

    print("=" * 50 + "\n")


def simpan_laporan():
    """Menyimpan laporan ke file teks (laporan_panen.txt)."""
    if not data_panen:
        print("\n[!] Belum ada data untuk disimpan.")
        return

    total = hitung_total(data_panen)
    rata_rata = total / len(data_panen)
    komoditas_tertinggi = max(data_panen, key=data_panen.get)
    komoditas_terendah = min(data_panen, key=data_panen.get)

    try:
        with open("laporan_panen.txt", "w", encoding="utf-8") as file:
            file.write("=" * 50 + "\n")
            file.write("      LAPORAN HASIL PANEN DIGITAL\n")
            file.write("=" * 50 + "\n")
            file.write(f"Total Hasil Panen  : {total:.2f} kg\n")
            file.write(f"Rata-rata Panen    : {rata_rata:.2f} kg/komoditas\n")
            file.write(f"Komoditas Tertinggi: {komoditas_tertinggi} ({data_panen[komoditas_tertinggi]} kg)\n")
            file.write(f"Komoditas Terendah : {komoditas_terendah} ({data_panen[komoditas_terendah]} kg)\n")
            file.write("-" * 50 + "\n")
            file.write(f"{'Komoditas':<15}{'Jumlah (kg)':<15}{'Kontribusi':<12}\n")
            file.write("-" * 50 + "\n")

            for komoditas, jumlah in sorted(data_panen.items(), key=lambda x: x[1], reverse=True):
                persentase = (jumlah / total) * 100
                file.write(f"{komoditas:<15}{jumlah:<15.2f}{persentase:.2f}%\n")

            file.write("=" * 50 + "\n")

        print("\n[✓] Laporan berhasil disimpan ke file 'laporan_panen.txt'")
    except IOError as e:
        print(f"\n[!] Gagal menyimpan laporan: {e}")


# ==================== MENU UTAMA ====================

def main():
    while True:
        print("\n=== MENU ===")
        print("1. Tambah data hasil panen")
        print("2. Lihat data hasil panen")
        print("3. Lihat laporan hasil panen")
        print("4. Simpan laporan ke file")
        print("5. Keluar")
        pilihan = input("Pilih menu (1/2/3/4/5): ").strip()

        if pilihan == "1":
            input_data()
        elif pilihan == "2":
            tampilkan_data()
        elif pilihan == "3":
            laporan()
        elif pilihan == "4":
            simpan_laporan()
        elif pilihan == "5":
            print("Program selesai.")
            break
        else:
            print("Pilihan tidak dikenali, coba lagi.")


if __name__ == "__main__":
    main()